// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9VBTHcUphcaLfYb7vmQyFkBss4lG8sQ4',
    appId: '1:921926634023:web:e17215102fcb1fe83bdc02',
    messagingSenderId: '921926634023',
    projectId: 'new-project-14d83',
    authDomain: 'new-project-14d83.firebaseapp.com',
    storageBucket: 'new-project-14d83.firebasestorage.app',
    measurementId: 'G-83D8ZEDJC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuG5OzbtNcZoRMuqRtonxzHx5ePkuHV9A',
    appId: '1:921926634023:android:151d7feffc475e213bdc02',
    messagingSenderId: '921926634023',
    projectId: 'new-project-14d83',
    storageBucket: 'new-project-14d83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9MLVkTl-d7czKoODF3LaU8QbgBlVH-_M',
    appId: '1:921926634023:ios:4b3c219ee0bc63e33bdc02',
    messagingSenderId: '921926634023',
    projectId: 'new-project-14d83',
    storageBucket: 'new-project-14d83.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9MLVkTl-d7czKoODF3LaU8QbgBlVH-_M',
    appId: '1:921926634023:ios:4b3c219ee0bc63e33bdc02',
    messagingSenderId: '921926634023',
    projectId: 'new-project-14d83',
    storageBucket: 'new-project-14d83.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );
}
